### ISSUE TITLE
Release 3

### ISSUE THREAD

**Issue by petterarvidsson** [konstructs/client#102]
- [x] Move to build with C++
- [x] Change GUI to use [nanogui](https://github.com/wjakob/nanogui)
- [ ] Change chunks to use std::shared_ptr

**Comment by nsg** [comment]
* The project is build with a C++11 compiler, and plenty of C code is rewritten to C++ in #103 
* The branch `feature-add-nanongui` (from PR #103) is build around nanogui.
* Plenty of `shared_ptr` in https://github.com/konstructs/client/blob/feature-add-nanongui/src/chunk_factory.h#L17 (from PR #103)

I will close this now, if there still is something specific open a new issue and assign it to the "Release 3" milestone.
