### ISSUE TITLE
Use scroll wheel to select items in the belt.

### ISSUE THREAD

**Issue by nsg** [konstructs/client#109]
Use scroll the mouse wheel to select items in the inventory belt.

**Comment by nsg** [comment]
Note: you need to do a local interpolation for this. The server latency is to large.

**Comment by Henningstone** [comment]
Needs the server to know which item is currently selected in the belt? Like I see, the server only needs to know what block we what to place, when we want to place a block. So what I mean, rather keep the server completely out of this?

**Comment by nsg** [comment]
Hm, we loses the ability for the server to change the selection for us. But I like the idea to simplify things... That do you think @petterarvidsson?

**Comment by Henningstone** [comment]
Hm, actually didn't think of the possibility that the server might want to change the selection… But wouldn't it be somehow confusing to the players if suddenly their selection changed, although they didn't do a thing? For me it would :P

**Comment by petterarvidsson** [comment]
I guess not, the client could send this information every time the user clicks (would add very little overhead). I don't think we use the information for anything in the server at the moment, so I would vote for doing it this way (unless we stumble up on something while implementing as often happens). Shared state is always a pain :-)
