### ISSUE TITLE
Show items in 3d

### ISSUE THREAD

**Issue by nsg** [konstructs/client#110]
Items in the inventory are not rotated atm, give them a nice rotation for a nicer 3d-look.
Give the selected item a little extra rotation.

**Comment by nsg** [comment]
![screenshot from 2015-12-26 21 21 23](https://cloud.githubusercontent.com/assets/16388/12007822/a1c927a0-ac16-11e5-9411-63453658a457.png)

Something like this, from the old client.

**Comment by petterarvidsson** [comment]
![screenshot from 2015-12-28 15 41 03](https://cloud.githubusercontent.com/assets/1921188/12020178/868b5030-ad79-11e5-9c4b-e4099e73c594.png)
@nsg Would you say this is in the right direction?

**Comment by petterarvidsson** [comment]
Second attempt 
![screenshot from 2015-12-28 17 30 05](https://cloud.githubusercontent.com/assets/1921188/12021718/548f1822-ad89-11e5-9f83-f970c319b1bd.png)

**Comment by nsg** [comment]
Looks better, something isn't looking completely right but I can't really figure out what.
If possible, maybe make it smaller and/or move them outside the box like in the c-version?
I like the rotation, looks much better!
If possible, can you reduce the spacing between the characters? "2 5" looks a little ugly :) Possible, I think the chars are a little to stretched wide compared to the old screenshot.

**Comment by petterarvidsson** [comment]
@nsg Like that:
![screenshot from 2015-12-28 17 51 04](https://cloud.githubusercontent.com/assets/1921188/12021969/9fda58f8-ad8b-11e5-85fb-5f9921c6410d.png)

**Comment by Henningstone** [comment]
The grass is a bit faily :P But that's a minor issue. All in all, this last one looks pretty good, I also prefer less aggressive rotation :+1:

**Comment by nsg** [comment]
Yes, much better! Something is a little weird with the text still but lets ignore that for know :)

**Comment by Henningstone** [comment]
In the c client, the text was in the center, now it is at the right. Maybe this is what you mean?

**Comment by petterarvidsson** [comment]
@nsg The text can be tweaked as much as you like by altering the values on line 385 in hud.cpp: 
```
make_character(d + i * 10 * 6, pair.first[0] - (float)offset*0.2 + 0.75f, pair.first[1] + 0.25f, 0.1, 0.2, text[index], 0.0);
```
The first 0.2 is the spacing,  0.1 is the width and the next 0.2 is the height. Feel free to tweak them until you are happy.

**Comment by nsg** [comment]
@petterarvidsson I will :)
