### ISSUE TITLE
Save players position correctly

### ISSUE THREAD

**Issue by Henningstone** [konstructs/client#117]
Only the z/x-Position is being saved, not the y-position (height)

**Comment by nsg** [comment]
From meta/players/test.json

```
"position":{"x":-150.75,"y":30.75,"rx":0.004203100223094225,"ry":4.747039794921875,"z":-152.75}
```

The problem is that your character falls down while the chunks are loading. The player is restored to the correct spot. A better solution is probably to wait for the chunk below to load, or, something similar.

**Comment by Henningstone** [comment]
So related to #98
