### ISSUE TITLE
Test Release 3

### ISSUE THREAD

**Issue by nsg** [konstructs/client#141]
All issues in the [Release 3](https://github.com/konstructs/client/milestones/Release%203) is now completed and it's almost time for a final release. After 3 long months I'm looking forward to try it out!

## Test it!

Windows:
Test the Windows packaged development version and make sure it runs.
https://bintray.com/artifact/download/konstructs/windows/konstructs-client.zip

Linux:
Test the Linux packaged development version and make sure it runs.
https://bintray.com/artifact/download/konstructs/linux/konstructs-client.tar.bz2

OS X (not required):
There are no packages yet, so there is nothing to test. A compile and a sanity check from master is nice to have but not required.

## Report problems

* Open a new issue report the problem.
* Add `[BUG R3]` to the subject for easy identification.
* Add `Ref #141` to the bottom of the issue.

Questions and any other questions, use this issue or [Gitter](https://gitter.im/konstructs/client)

**Comment by Henningstone** [comment]
I can do the windows test :)

**Comment by nsg** [comment]
Awesome!

**Comment by nsg** [comment]
Thank you all for all the help, both Linux and Windows version are tested and verified working!
