### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by jonasekl** [konstructs/client#142]
fe3l, fel fel

**Comment by Henningstone** [comment]
A somehow interesting bug, but could you be a bit more precise? :)

**Comment by nsg** [comment]
Hehe, it's just a friend testing out a feature :P I will close this now :)
Thank you @jonasekl :)

**Comment by jonasekl** [comment]
Sorry @Henningstone I should have been way more precise. Like @nsg mentions, this was in no way a proper issue :)

**Comment by Henningstone** [comment]
No problem, I was only joking ;) Somehow I know that it isn't a proper issue :smile:
