### ISSUE TITLE
[BUG R3] Missing dll's and errors under Windows

### ISSUE THREAD

**Issue by Henningstone** [konstructs/client#145]
> The program cannot be run, because libgcc_s_sjlj-1.dll is missing on the computer. Reinstalling the application could solve the problem.

error message: https://imgur.com/tzJEbz8

> The program cannot be run, because libwinpthread-1.dll is missing on the computer. Reinstalling the application could solve the problem.

error message: https://imgur.com/oaKisd3

Ref #141

**Comment by nsg** [comment]
This is a build with `-static-libgcc`, it this one working for you?

[konstructs-client.zip](https://github.com/konstructs/client/files/74819/konstructs-client.zip)

**Comment by Henningstone** [comment]
I edited my post, now there is a second library missing.

**Comment by nsg** [comment]
Ah, that's nice ... I'm a little annoyed that the filesize went from 5M to 30M, well, at least it works :) I will see that I can do about the second one now.

**Comment by Henningstone** [comment]
Really? For me, the size didn't change at all oO

**Comment by nsg** [comment]
Windows do not implement POSIX threads, I thought modern MinGW contained what we needed, I guess not :)

This project will probably do the trick:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/

Is the build still a 32 bin binary, or did we change that? I think it's "dwarf" you need. Try to download the popular one, rev1. You will find the lib under bin/ in the archive. Try to move it next to konstructs-client.exe and see it if works better now.

**Comment by Henningstone** [comment]
The missing-dll-error is gone now, but instead I got this one: https://i.imgur.com/dTRzcez.png
I have no clue how to translate "Prozedureinsprungpunkt"... maybe something like "entrance point"?

**Comment by nsg** [comment]
That was a hard one :) I will see what I can do.

**Comment by Henningstone** [comment]
The project you mentioned has also this library "libstdc++-6.dll", and when using this instead it doesn't work, but it changes the error message oO https://i.imgur.com/t1JbqFB.png

**Comment by petterarvidsson** [comment]
Are you using the DLL files from the cross compiler used to build the binary? Otherwise try that, because it should be impossible for such a DLL to be missing functions since it was used for linking.

**Comment by nsg** [comment]
Good idea, this is the files from the environment we cross compile the binary from.
[pth_libcpp.zip](https://github.com/konstructs/client/files/74882/pth_libcpp.zip)

@Henningstone can try to run it with these?

* Original binary + libstdc++-6.dll + libwinpthread-1.dll
* The modified on included here + libwinpthread-1.dll

**Comment by Henningstone** [comment]
That's so weird. The original binary doesn't work in every case (first dll missing). The binary from this issue is *not* missing the first dll, but this thread thingy. Now I give him the libwinpthread you just uploaded, he is having the error message with "Prozedureinsprungpunkt" in libstdc++-6.dll again. Well until there. Then, I give him the new libstdc++-6.dll you just uploaded, and he is missing the first library again?!

(first library/dll == "libgcc_s_sjlj-1.dll")

**Comment by petterarvidsson** [comment]
Is the original binary compiled in the same environment as the files in pth_libcpp.zip?

**Comment by nsg** [comment]
@petterarvidsson Same os/packages installed but there is a possibility that we got a little newer packages b/c I rebuilt the container. 

Lets make a special build with everything included, everything build from the same environment.

* With `-static-libgcc`: [konstructs-client-mod.zip](https://github.com/konstructs/client/files/74918/konstructs-client-mod.zip)
* Like the original: [konstructs-client.zip](https://github.com/konstructs/client/files/74919/konstructs-client.zip)

@Henningstone can you try the builds above?

**Comment by Henningstone** [comment]
Both give the same error: "libnanogui.dll is missing on the system"

**Comment by nsg** [comment]
One step closer to the solution then, I hope :) I will investigate.

In the meantime, can you figure out what dll:s we really need? I guess `libstdc++-6.dll`, `libwinpthread-1.dll` and `zlib1.dll`. If you remove the rest, is it complaining?

**Comment by Henningstone** [comment]
I removed all except them: https://i.imgur.com/XdoaT9u.png
I think these are the ones we really need.

**Comment by nsg** [comment]
Ok, thank you!

**Comment by nsg** [comment]
Okay, we have a new build now. I fixed #144 so I hope this solved the problem under windows as well :)

New fresh build, build like the original with the dll:s you specified included.

[konstructs-client.zip](https://github.com/konstructs/client/files/74933/konstructs-client.zip)

@Henningstone is this one working?

**Comment by petterarvidsson** [comment]
I get the following when running in wine (the login gui show, but this happens when I press connect):
```
At '/build/src/client.cpp:38' in function 'open_connection' occurred error 'gethostbyname': Success
```

**Comment by nsg** [comment]
I have the same problem, I wonder if it's a windows or wine problem :)

**Comment by Henningstone** [comment]
For me aswell:
>WSAGetLastError: 10093
At '/build/src/client.cpp:38' in function 'open_connection' occurred error 'gethostbyname': No error

**Comment by nsg** [comment]
Looks like we need to init the dll like we did in the old c client, I guess something was lost in the rewrite.

http://stackoverflow.com/a/16478146/621099

**Comment by petterarvidsson** [comment]
Oh, did I remove that. Sorry!

**Comment by nsg** [comment]
I get this in wine now:

```
Assertion failed!

Program: Z:\home\nsg\code\konstructs\client\package\konstructs-client\konstructs-client.exe
File: /build/dependencies/nanogui/ext/eigen/Eigen/src/Core/DenseStorage.h, Line 86

Expression: (reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"

abnormal program termination
```

With this file: [konstructs-client.zip](https://github.com/konstructs/client/files/74940/konstructs-client.zip)

@Henningstone can you see if it's a wine of windows problem :)

**Comment by petterarvidsson** [comment]
@nsg Seems there are some stuff we might need to fix with eigen: http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html

I'll take a look at that tonight. Might be triggered by wine though.

**Comment by nsg** [comment]
@petterarvidsson Yes, I was just reading the page and started to realize the same thing. I hope this is only triggered with wine, we will see :)

**Comment by Henningstone** [comment]
First, it connects. But then it crashes and prints the same error into the console.

**Comment by petterarvidsson** [comment]
I think we should maybe just do this http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html#getrid. We are not doing much vector math, so I think the autovectorization is not really providing any speed-up.

**Comment by petterarvidsson** [comment]
http://eigen.tuxfamily.org/index.php?title=FAQ#I_disabled_vectorization.2C_but_I.27m_still_getting_annoyed_about_alignment_issues.21

**Comment by nsg** [comment]
@Henningstone ok, looks like we need some @petterarvidsson magic to fix this then :)
@petterarvidsson okay, I will read the pages and educate my self!

I will push these changes I have made to a PR.

**Comment by petterarvidsson** [comment]
@nsg It seems this would be the right thing to do for us:
```
Define EIGEN_DONT_ALIGN (this requires Eigen 2.0.6 or later). That disables all 128-bit alignment code, and in particular everything vectorization-related. But do note that this in particular breaks ABI compatibility with vectorized code.
```

**Comment by nsg** [comment]
@petterarvidsson oh, where do I put this define, in CMAKE when we build the lib, or is it a #define?

**Comment by petterarvidsson** [comment]
Good question :-)

I guess it would have to be in cmake somehow. Best would be in top level if possible, otherwise in the subproject itself

**Comment by nsg** [comment]
@petterarvidsson what do you think, only for WIN32 or do we want that for everything?

**Comment by nsg** [comment]
Playing the game in wine!

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3a71883..eda39d8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,6 +18,7 @@ endif()
 
 if(MINGW)
   add_definitions(-DWIN32)
+  add_definitions(-DEIGEN_DONT_ALIGN)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unknown-pragmas")
 endif()
```

**Comment by nsg** [comment]
@Henningstone When you have time, this one works for me:

[konstructs-client.zip](https://github.com/konstructs/client/files/74954/konstructs-client.zip)

**Comment by Henningstone** [comment]
Yay, well done! :tada: 
The game works on windows, and has a extremely awesome performance! Even without disabling the visual designs (dwm) which broke everything before. So for release 3, you can remove the recommendation to disable it from the website :)

**Comment by nsg** [comment]
Awesome!

**Comment by petterarvidsson** [comment]
:clap: @nsg @Henningstone

**Comment by Henningstone** [comment]
you did also very well :clap:
