### ISSUE TITLE
Crash on OS X on chunk loading

### ISSUE THREAD

**Issue by nsg** [konstructs/client#154]
> auto maxIter = chunks.begin() + max;

https://github.com/konstructs/client/blob/master/src/client.cpp#L165

This line causes a problem under OS X. This crashed the client when we received the first chunks. I assume we got less than 10 chunks and `chunks.begin() + max` pointed outside chunks allocated memory.

**Comment by nsg** [comment]
Thank you @nflx for the help testing and debugging this.

**Comment by petterarvidsson** [comment]
This bug is possibly fixed by #161, but I can not test it since I lack a OSX compatible device. Help with testing this would be highly appreciated!
