### ISSUE TITLE
Client doesn't start on Windows

### ISSUE THREAD

**Issue by petterarvidsson** [konstructs/client#155]
It complains about something with open GL.

**Comment by derhuerst** [comment]
Please provide this "something about OpenGL" here, to help the people here to identify the problem. Copy & paste the error, including possible stack traces here. Also, information on how to reproduce this issue is helpful, for example which version/release/tag you used.

**Comment by petterarvidsson** [comment]
It's a Windows 7 64 bit. The error looks like this:
![screenshot](https://cloud.githubusercontent.com/assets/1921188/13198158/e0db3138-d801-11e5-8e54-0bdb13d02c89.PNG)

**Comment by petterarvidsson** [comment]
The issue appears when trying to start the latest version.

**Comment by nsg** [comment]
@petterarvidsson Are we sure that the system supports OpenGL 3.3?

**Comment by petterarvidsson** [comment]
Nope, not sure. Got the report from a friend, will see if I can gather more information later on. An early guess would be something related to us now requiring a slightly newer version of Open GL.

**Comment by nsg** [comment]
Agree, that's my guess.
https://www.opengl.org/registry/specs/ARB/wgl_create_context.txt

Looks like 3+ is needed for that, or even possible 3.2+ ... I did not read the entire page :)

**Comment by nsg** [comment]
Maybe check `glGetString(GL_VERSION)` or something similar and fail with a nice message for older systems/drivers.

**Comment by petterarvidsson** [comment]
@nsg Are we building 32 bit or 64 bit binaries?

**Comment by nsg** [comment]
@petterarvidsson 

32-bit for Windows
https://github.com/konstructs/client/blob/master/package/Makefile#L69

**Comment by petterarvidsson** [comment]
Oh btw, old version of the client worked.

**Comment by nsg** [comment]
@petterarvidsson old like version 2 before we upgraded to 3.3? Sounds like an to old computer/driver then :\

**Comment by petterarvidsson** [comment]
@derhuerst I have now tried to gather up some more info, but will try to get more later on. Are you using windows? If so, have you been able to start the latest version of the client or maybe this is a broader problem? I'm having a bit of a problem testing only having Linux on my computer.

**Comment by petterarvidsson** [comment]
@nsg Yes exactly!

**Comment by nsg** [comment]
@petterarvidsson I made this: https://github.com/konstructs/client/pull/156

**Comment by derhuerst** [comment]
@petterarvidsson

> Are you using windows?

No, sorry. I just responsed like this because another issue regarding a bug, without any specific information, has been opened. I a. didn't notice that you are a core contributor and b. assumed that you have more info than just a screenshot.

**Comment by petterarvidsson** [comment]
@derhuerst No worries. I agree it was a really crappy bug report :-) Thank you for helping out and making sure issues are in good shape. It is highly appreciated!

**Comment by petterarvidsson** [comment]
The graphics card is quite good and seems to support Open GL 4.4, so very recent drivers. Must be something else that is failing!

![screenshot2](https://cloud.githubusercontent.com/assets/1921188/13198771/2d67d546-d812-11e5-932e-ea15d50ec3c7.PNG)

**Comment by petterarvidsson** [comment]
One theory is that since this card supports Optimus konstructs is started using the embedded low power, but slow, card. This is a binary with the correct defines as explained here: http://www.glfw.org/docs/latest/compile.html#compile_options_win32

[konstructs-client.zip](https://github.com/konstructs/client/files/139373/konstructs-client.zip)

**Comment by nsg** [comment]
@petterarvidsson did you find out if this solved it?

**Comment by petterarvidsson** [comment]
@nsg Not yet. I am thinking that maybe we should activate this for everyone anyway, I mean we would always want to use the powerful graphics card anyway?

**Comment by nsg** [comment]
@petterarvidsson Agree, I assume that the option has no/negative effect for other systems.

**Comment by petterarvidsson** [comment]
Btw, an update. The client didn't crash after adding the Optimus stuff. it wasn't reported to fully work either, but I think we should add it to the main build.

**Comment by nsg** [comment]
Sounds good to me!
