### ISSUE TITLE
Hold shift to prevent falling down from a block

### ISSUE THREAD

**Issue by nsg** [konstructs/client#170]
Now when flying is disabled I realized the need for a function I was missing from Minecraft, the ability to hold down shift to prevent the character from falling of a block edge. This do not necessity need to be the shift key, but, it's a convenient and well known key so I think we use that as well :)

**Comment by petterarvidsson** [comment]
I have implemented this in #182. I have noticed that in most other games the player is allowed to hang outside of the block both normally and in sneak mode, allowing to build blocks below yourselves when standing on an edge. This has not been implemented. Maybe we should open a new issue regarding this?

**Comment by nsg** [comment]
@petterarvidsson possible, I think we consider this one closed and if we feel the need to implement that functionality we will open a new issue like you suggested.
