### ISSUE TITLE
Block damage

### ISSUE THREAD

**Issue by petterarvidsson** [konstructs/client#185]
- Show blocks in the world that are damage differently in some way. Maybe an overlay texture?
- Show blocks in the HUD that are damage differently as well, but maybe some type of health bar is appropriate here?

**Comment by nsg** [comment]
* Yup, the simplest way is probably just to blend `hp/max_hp %` of the textures together, a better looking alternative is probably to use several different textures and blend them.
* I like the idea with a progress bar!

**Comment by nsg** [comment]
@petterarvidsson 

Consider #184, #188 and #189 (and probably more), I consider this issue resolved. Do you agree?

**Comment by petterarvidsson** [comment]
@nsg I agree. Client seems to be fully functional now!
