### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by petterarvidsson** [konstructs/client#186]
Add a new voxel model for tools. Maybe tools should be like "plants" but rather than a cross, just be a flat surface. For the hud, I think they can be rendered in the same flat way as "plants".

**Comment by nsg** [comment]
Agree!

**Comment by nsg** [comment]
@petterarvidsson I guess a model will be more useful/better looking for this. Close this maybe, or?

**Comment by petterarvidsson** [comment]
Let's close it.
