### ISSUE TITLE
Won't run on Ubuntu 16.04 LTS - Possible incorrect OpenGL version?

### ISSUE THREAD

**Issue by capot1948** [konstructs/client#223]
installed the Konstructs client snap on the above system this evening. Will not run from the menu and when run from the CLI the output is:
```
chris@localhost:/snap/bin$ konstructs-client
Welcome to Konstructs Client
----------------------------

Snap (snapcraft) is still a new package format and there are still
problems with OpenGL applications, like Konstructs.

The system will output some debug information to help us to track
down possible problems, please report crashes to:
https://github.com/konstructs/client/issues
Check for simular existing issues before you create a new one.

Some of your enviroment:
/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/dri:/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/mesa-egl:/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/mesa:/var/lib/snapd/lib/gl::/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu:/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/mesa:/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/mesa-egl::/snap/konstructs-client/7/lib:/snap/konstructs-client/7/usr/lib:/snap/konstructs-client/7/lib/x86_64-linux-gnu:/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu
/snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/dri
/var/lib/snapd/lib/gl:
7
amd64
:1

A little about your system:
gnome
Linux localhost 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

List with libGL.so are available:
	libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
	libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
	libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa/libGL.so
ls: cannot access '/var/lib/snapd/lib/gl:': No such file or directory
I will start the client now!
-------------------------------------------------------
libGL: OpenDriver: trying /snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/dri/tls/i965_dri.so
libGL: OpenDriver: trying /snap/konstructs-client/7/usr/lib/x86_64-linux-gnu/dri/i965_dri.so
libGL: Can't open configuration file /home/chris/snap/konstructs-client/7/.drirc: No such file or directory.
libGL: Using DRI2 for screen 0
GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
Caught a fatal error: Could not create an OpenGL 3.3 context!
-------------------------------------------------------
Did the client crash? If yes please report the problem.
```

I checked my OpenGL version
chris@localhost:/snap/bin$ glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 11.2.0
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

If I read this correctly my version of OpenGL is only 2.1 therefore the client will not run on my system.

**Comment by nsg** [comment]
Agree, if I'm not mistaken it do look like your driver and/or gfx card only provides 2.1.

**Comment by capot1948** [comment]
On Wed, 2016-11-16 at 12:05 -0800, Stefan Berggren wrote:
> Agree, if I'm not mistaken it do look like your driver and/or gfx
> card only provides 2.1.

Thanks Stefan, that's what I thought. 

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Chris
KeyID 0xE372A7DA98E6705C
31.11972; -97.90167 (Elev. 1092 ft)
15:04:51 up 5:27, 1 user, load average: 0.62, 0.23, 0.14
Ubuntu 16.04.1 LTS, kernel 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26
19:39:52 UTC 2016
