### ISSUE TITLE
"Error, no shaders for chunk.frag found." when running

### ISSUE THREAD

**Issue by discordianfish** [konstructs/client#231]
Hi,

just came across this and wanted to try it but got the error above. Am I suppose to download the shaders somewhere?

**Comment by nsg** [comment]
They are supposed to be bundled with the game, are you running it on Linux, Win, OSX. How is it installed, zip, deb, rpm, snap, ...?

**Comment by Henningstone** [comment]
None of the downloadable Release 8 packs does actually contain the shaders folder, I also realized that but though "well, let's just grab it from the repo"

**Comment by nsg** [comment]
Yup, looks like it's missing. I will try to release a new version with it included in a day or so.

**Comment by discordianfish** [comment]
Awesome, thanks!
