### ISSUE TITLE
Display inventory package

### ISSUE THREAD

**Issue by nsg** [konstructs/client#51]
If:
* Receive `O` package, or, `E` was pressed.

Then:
* Display a 16x8 inventory on the screen. The server sends a list of items to display: -1, 0, 1, 2 ...

`-1` is "disabled", this slot is hidden.
`0` is an empty slot
`1+` to display a block

**Comment by nsg** [comment]
@petterarvidsson We have talked about to change the `I` package to send data to both inventories. Just to be clear, is this correct:

Currently the `I` package is defined like this:
```
if (sscanf(line, "I,%d,%d,%d", &pos, &amount, &id) == 3) {
```

And we intend to change it to this:
```
if (sscanf(line, "I,%d,%d,%d,%d", &inv, &pos, &amount, &id) == 4) {
```
(where `inv` is the inventory number, 0 for the belt and 1 for the new inventory)

I this correct?

Should we drop the `O` package completely and just open the external inventory for any package that updates "inventory 1"? Or do we like to keep them separated?

**Comment by petterarvidsson** [comment]
That looks correct. I'd say let's drop the O field for now.

**Comment by nsg** [comment]
I did something like this, to keep comparability with the current server:

```
#if PROTOCOL_VERSION == 3
  // code for v3
#else
  // code for v4
#endif
```
