### ISSUE TITLE
Improve network handling

### ISSUE THREAD

**Issue by petterarvidsson** [konstructs/client#77]
- [ ] Don't close client on network errors
- [ ] Show any error message from the server to the end user

**Comment by Henningstone** [comment]
Maybe close client connection indeed, but the client should rather disconnect with a message for the user than exiting.

**Comment by nsg** [comment]
We can't reopen a closed socket, but we can open a new one. Makes no difference for the user :)
The simplest approach is just to fall back to "the main menu" again and display an appropriate message from the server there.

**Comment by petterarvidsson** [comment]
I'd say #180 solves this one following @Henningstone's comment. It always falls back to the connection menu whenever there is a network failure and let's the user reconnect.
