### ISSUE TITLE
Add clientside prediction

### ISSUE THREAD

**Issue by Henningstone** [konstructs/client#82]
What would you say about a system which predicts the results of the local client's actions instead of waiting for the server's respond, but then update that predicted stuff with the server's messages when they're received? That might give players a better and smoother gameplay experience in certain cases.
For example, placing/removing blocks could be displayed instantly and sent to the server then, and as soon as the server's respond comes in, the "predicted" blocks are updated with that if it differs from what we predicted.
It would be an upgrade of the "ghostblock" I think, and should give big improvements to players with high latency. To be honest, is there a reason for displaying an invisible block instead of the actual block?

**Comment by nsg** [comment]
There are no way to predict most actions. The client has tree mouse actions "primary, secondary and tertiary (E) mouse click". That state is sent together with the selected coordinates. There are no way for the client to know what "primary mouse click" will do. This is the biggest downside with the server driven logic.

The ghost blocks are a experiment to predict block placements, I and @petterarvidsson had a little different of opinion how to display it and what you see is the middle ground. You can change `GHOST_BLOCK_MIN_AGE` to `0` to see my preferred version :) The "invisible" ghost blocks helps when you are building quickly, see the video https://www.youtube.com/watch?v=7HofYSIKlbw

We have discussed the option for the server to send block meta data to the client to help the client to guess better but that can be tricky to implement on a good way. We like to keep the client as dumb as possible to, for example, make it possible to write a plugin that changes the meanings of the mouse buttons.

**Comment by Henningstone** [comment]
Oh ok, if quite every behaviour should be changeable by the server, it is indeed impossible. I just thought that at lease block placement won't change.

**Comment by Henningstone** [comment]
I just found a bug with the ghost blocks: I ghost block is being placed too when placing an "empty" block, so basically nothing.

**Comment by nsg** [comment]
See PR #86, I and @petterarvidsson had a discussion earlier this week and this is another take on the problem, basically what you suggested :)
