### ISSUE TITLE
Custom key bindings

### ISSUE THREAD

**Issue by Henningstone** [konstructs/client#84]
How did you imagine to implement custom key bindings? Will there be a menu, or maybe some sort of command line to change them? (I'd actually like to see a command line to access the config directly... And to be honest, having the config through #defines is rather crap, see #85)

**Comment by nsg** [comment]
Initially in the configuration file (when that's implemented), in the future a more user-friendly GUI is probably a good idea.

**Comment by Henningstone** [comment]
But there is no configuration file yet, is it? Implementing one shouldn't be too hard.

**Comment by nsg** [comment]
Exactly!
