### ISSUE TITLE
Proper config system

### ISSUE THREAD

**Issue by Henningstone** [konstructs/client#85]
The current config system is obviously very alpha. Of cause the game needs a proper config that can be changed by the user, for example through a command line or even a GUI.
Are there any ideas yet? I'd have a few... Dunno how good they are, though.

**Comment by nsg** [comment]
My idea is to find a simple to use library that implements a ini parser (with a good license), and move the relevant configuration options there. The game will read the configuration file on start and populate a global struct. This will also allow the future possibility to change settings on the fly.
