### ISSUE TITLE
some int-functions with no return

### ISSUE THREAD

**Issue by Henningstone** [konstructs/client#90]
In `main.c`, the functions `int load_shaders(....)` and `int load_textures()` are declared with an integer return, but there is no `return <int>` in their body.

See here: [(watch in code)](https://github.com/konstructs/client/blob/master/src/main.c#L2141-L2248)

**Comment by petterarvidsson** [comment]
I agree, it would make sense to change them to void.

**Comment by nsg** [comment]
Fixed in https://github.com/konstructs/client/pull/92
